// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqk73uFlFaNv63aSq6Mm0hpzEE_C7A9rM',
    appId: '1:703198613161:web:7526e094d8009e2b94e3b8',
    messagingSenderId: '703198613161',
    projectId: 'communitycaht',
    authDomain: 'communitycaht.firebaseapp.com',
    storageBucket: 'communitycaht.appspot.com',
    measurementId: 'G-Y0B8D5V2RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArBC5CU2pk119Vyc87MWqdkX2y2V2EzZg',
    appId: '1:703198613161:android:de00a8d905ea79d494e3b8',
    messagingSenderId: '703198613161',
    projectId: 'communitycaht',
    storageBucket: 'communitycaht.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwHYBBmpFaqLZIfIOHmpgbtJEhl3hi9_c',
    appId: '1:703198613161:ios:6c75e50a20635a2794e3b8',
    messagingSenderId: '703198613161',
    projectId: 'communitycaht',
    storageBucket: 'communitycaht.appspot.com',
    iosBundleId: 'com.example.communitychat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwHYBBmpFaqLZIfIOHmpgbtJEhl3hi9_c',
    appId: '1:703198613161:ios:ab8e48e77b46506d94e3b8',
    messagingSenderId: '703198613161',
    projectId: 'communitycaht',
    storageBucket: 'communitycaht.appspot.com',
    iosBundleId: 'com.example.communitychat.RunnerTests',
  );
}
